### ISSUE TITLE
Streamline Network Deploy - rolling/restart update in 1 hour

### ISSUE THREAD

**Issue by john-harmony** [harmony-one/experiment-deploy#188]
## Overview
Harmony has a number of tools used to deploy a network. This ticket is to improve and automate these tools with the goal of reducing deployment time and automating a number of manual steps.

## Task Overview

- [ ] Consolidate Knowledge of deployment of all components
- [ ] Create a validation checklist for all components
- [ ] Automate Deployment Steps
- [ ] Automate Validation Steps
- [ ] Deployments are run and automated by 

## Acceptance Criteria Per Component
- [ ] Deployment Instruction Page Created
- [ ] Components added into deployment pipeline
- [ ] Validation Script Updated
- [ ] Watchdog Page Created for Component Status
- [ ] Deployment Instructcions added to docs.harmony.one
- [ ] Component Troubleshooting added to docs.harmony.one

## Component Overview Checklist

- [ ] Harmony Protocol
  - [ ] CLI
  - [ ] Wallet
 - [ ] Node.sh
- [ ] Block Explorer Deployment
- [ ] Sentry Node Deployment
- [ ]  Faucet Deployment
- [ ] Watchdog Deployment
- [ ]  Staking Explorer
- [ ] Harmony Chrome Extension
